/*
 * @Date: 2020-06-05 10:03:46
 * @LastEditors: Please set LastEditors
 * @LastEditTime: 2020-10-25 01:03:09
 * @FilePath: /project/src/store/redux/ActionTypes.js
 */ 
export const Status = {
    INIT:'INIT',
    LOADING: 'LOADING',
    SUCCESS:'SUCCESS',
    ERROR:'ERRPR'
}

export const ActionTypes = {
    BASE: 'BASE', //  初始类型
    INDEXBANNER:'INDEXBANNER', // 首页轮播
    HISTORYTSPORTRECORD: 'HISTORYTSPORTRECORD', // 昨日战绩
    SPORTSLIST: 'SPORTSLIST', // 赛事列表
    RECOMMENDSOPRTS: 'RECOMMENDSOPRTS', // 热门赛事
    PROMOTIONTYPE: 'PROMOTIONTYPE', // 活动种类
    PROMOTIONLIST: 'PROMOTIONLIST',  // 活动列表
    NEWSLIST: 'NEWSLIST', // 资讯列表
    USERINFO:'USERINFO', // 用户信息
    SPORTSFOLLOW: 'SPORTSFOLLOW', // 体育关注
    LOTTERYFOLLOW: 'LOTTERYFOLLOW', // 彩票关注
    SPORTSCOLLECTION: 'SPORTSCOLLECTION', // 体育收藏
    USERMESSAGE: 'USERMESSAGE', // 用户消息
    RECOMMENDLOTTERY: 'RECOMMENDLOTTERY', //推荐彩票
    PROFESSORRECOMMENDLOTTERY:'PROFESSORRECOMMENDLOTTERY',// 专家推荐
    HISTORYLOTTERY: 'HISTORYLOTTERY', // 历史开奖
    LOTTERYDETAIL:'LOTTERYDETAIL', // 开奖详情
    LOTTERYLIST: 'LOTTERYLIST', // 彩票列表,
    LOTTERYCATEGORY: 'LOTTERYCATEGORY', // 彩种，
    SPORTSINFORMATION: 'SPORTSINFORMATION', // 赛事情报
    SPORTSLEAGUELIST: 'SPORTSLEAGUELIST', // 联赛列表
    SPORTSGETHANDICALIST: 'SPORTSGETHANDICALIST', // 盘口数据
    NEWSDETAIL:'NEWSDETAIL', // 资讯详情,
    PROMOTIONDETAIL:'PROMOTIONDETAIL', // 活动详情
    NEWSCOMMENTLIST:'NEWSCOMMENTLIST', // 新闻评论列表
    UPDATENEWSCOMMENT: 'UPDATENEWSCOMMENT', // 更新评论数
    WELFAREAPPLYLIST:'WELFAREAPPLYLIST', //福利申请列表
    HISTORYINDEXLOTTERY: 'HISTORYINDEXLOTTERY', // 首页昨日战绩彩票
    ASIANSPORTSINDEXLIST:'ASIANSPORTSINDEXLIST', // 亚盘盘口数据
    EROUPSPORTSINDEXLIST: 'EROUPSPORTSINDEXLIST', // 欧盘盘口数据
    SIZESPORTSINDEXLIST: 'SIZESPORTSINDEXLIST', // 让球盘口数据
    ASIANSPORTSINDEXDETAIL:'ASIANSPORTSINDEXDETAIL', // 亚盘详情
    SPORTSTEXTLIVE:'SPORTSTEXTLIVE', // 文字直播
}

export const serverUrl= 'http://localhost:10000'
// export const serverUrl= 'http://192.168.3.32:10000'
